version: "2"
#
# Services
#
services:
   transaction-service:
      build: ./transaction-service/
      volumes:
        - ./docker/transaction-service/config:/config
      ports:
        - 8085:8085
      networks:
          - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true