---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      DriverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://postgresdb:5432/postgres
      username: postgres
      password: postgres
- com.networknt.eventuate.common.impl.sync.AggregateCrud:
  - com.networknt.eventuate.client.EventuateLocalDBAggregateCrud
- com.networknt.eventuate.common.impl.AggregateEvents:
  - com.networknt.eventuate.client.KafkaAggregateSubscriptions
- com.networknt.eventuate.common.impl.AggregateCrud:
  - com.networknt.eventuate.common.impl.adapters.SyncToAsyncAggregateCrudAdapter
- com.networknt.eventuate.common.SnapshotManager:
  - com.networknt.eventuate.common.SnapshotManagerImpl
- com.networknt.eventuate.common.EventuateAggregateStore:
  - com.networknt.eventuate.common.impl.EventuateAggregateStoreImpl
- com.networknt.eventuate.queryservice.customer.CustomerViewRepository:
  - com.networknt.eventuate.queryservice.customer.CustomerViewRepositoryImpl
- com.networknt.eventuate.queryservice.customer.CustomerQueryService:
  - com.networknt.eventuate.queryservice.customer.CustomerQueryService
- com.networknt.eventuate.queryservice.customer.CustomerInfoUpdateService:
  - com.networknt.eventuate.queryservice.customer.CustomerInfoUpdateService
- com.networknt.eventuate.customer.view.CustomerQueryWorkflow:
  - com.networknt.eventuate.customer.view.CustomerQueryWorkflow
- com.networknt.eventuate.event.EventHandlerProcessor:
  - com.networknt.eventuate.event.EventHandlerProcessorDispatchedEventReturningVoid
  - com.networknt.eventuate.event.EventHandlerProcessorDispatchedEventReturningCompletableFuture
  - com.networknt.eventuate.event.EventHandlerProcessorEventHandlerContextReturningCompletableFuture
  - com.networknt.eventuate.event.EventHandlerProcessorEventHandlerContextReturningVoid
- com.networknt.eventuate.client.SubscriptionsRegistry:
  - com.networknt.eventuate.client.SubscriptionsRegistryImpl
- com.networknt.eventuate.account.command.account.Account:
  - com.networknt.eventuate.account.command.account.Account
