version: "2"
#
# Services
#
services:

   query-service:
      build: ./query-service/
      volumes:
        - ./docker/query-service/config:/config
      ports:
        - 8082:8082
      networks:
          - localnet
# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true